# Generated by Django 5.0.2 on 2024-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.BooleanField(null=True, verbose_name=False),
        ),
    ]
