# Generated by Django 5.0.2 on 2024-04-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.BooleanField(null=True),
        ),
    ]
