# Generated by Django 5.0.2 on 2024-04-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
