# Generated by Django 5.0.2 on 2024-04-02 22:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_email_verified',
            new_name='email_confirmed',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmation_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
