# Generated by Django 5.0.2 on 2024-04-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_is_email_verified_customuser_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_confirmation_token',
            field=models.CharField(default='', max_length=50),
        ),
    ]
