# Generated by Django 5.0.2 on 2024-04-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_email_confirmation_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(default='', max_length=150),
        ),
    ]
