# Generated by Django 5.0.2 on 2024-05-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_address_customuser_city_customuser_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
