# Generated by Django 5.0.2 on 2024-03-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover_picture',
            field=models.FileField(blank=True, null=True, upload_to='covers'),
        ),
    ]
