# Generated by Django 5.0.2 on 2024-03-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('video', '0003_video_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
