# Generated by Django 5.0.2 on 2024-04-05 23:40

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_remove_video_category_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(max_length=10, null=True, verbose_name=category.models.Category),
        ),
    ]
