# Generated by Django 5.0.2 on 2024-05-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_alter_video_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videoage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='age',
            field=models.IntegerField(choices=[(1, '6'), (2, '12'), (3, '16'), (4, '18')], null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='release_year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
